### PR TITLE
Change CRISPResso_status.txt format to JSON

### PR DESCRIPTION
**Pull request by mbowcut2**
This PR changes the `CRISPResso_status.txt` file format to JSON.

### CODE REVIEW

**Review by Colelyman — CHANGES_REQUESTED** [review]
This looks great to me! The only thing that I would suggest is changing the file extensions in the other tools as well, e.g. https://github.com/edilytics/CRISPResso2/blob/master/CRISPResso2/CRISPRessoWGSCORE.py#L367

**Comment by mbowcut2** [comment]
@Colelyman thanks! I knew I was missing something.

**Review by Colelyman — APPROVED** [review]

**Comment by mbowcut2** [comment]
- [ ] Add `crispresso_results.json` to integration test expected results

**Comment by mbowcut2** [comment]
Integration tests pass on branch `status_json`

**Pull request merged**
