### PR TITLE
No pool

### PR DESCRIPTION
**Pull request by Snicker7**
When there is only a single process (-p 1), don't use the multiprocessing library. (Required for use on AWS lambda)

### CODE REVIEW

**Review by Colelyman — CHANGES_REQUESTED** [review]
I think this looks great! We should probably implement the same thing for the `run_function_on_array_chunk_parallel` and `run_pandas_apply_parallel` functions, because I would imagine that they would throw the same error.

No problem if you aren't able to get to this @Snicker7, one of the rest of us can take care of it.

**Comment by Colelyman** [comment]
Also, for some reason these changes put the logger in a bad state where the log messages are repeated (once with the correct formatting, and another time with the incorrect formatting), see the attached screenshot. Note that this only seems to happen in single threaded mode `-p 1`.
Screen Shot 2024-06-13 at 10 38 25 AM

**Comment by Snicker7** [comment]
New fix resolves logger issue.

**Comment by Colelyman** [comment]
Good find, thanks @Snicker7!

**Review by Colelyman — APPROVED** [review]

**Pull request merged**
