### PR TITLE
GitHub actions integration tests

### PR DESCRIPTION
**Pull request by Snicker7**
Add github actions for integration tests. If everyone could pull "github-actions-integration-tests" to their branches and try pushing any changes your making. It would be good to make sure this the actions are working before it's in master.

### CODE REVIEW

**Review by Colelyman — APPROVED** [review]
This looks good to me! The only thing is that on the check for the final commit it looks like it is only running pylint. Am I missing the integration and unit tests somewhere?

I was trying to resolve the apparent "merge conflicts" (which was weird because there were no changes in CRISPRessoCORE.py...) and ended up adding a whole bunch of noise to this diff. Sorry about that!

**Comment by Snicker7** [comment]
> This looks good to me! The only thing is that on the check for the final commit it looks like it is only running pylint. Am I missing the integration and unit tests somewhere?
> 
> I was trying to resolve the apparent "merge conflicts" (which was weird because there were no changes in CRISPRessoCORE.py...) and ended up adding a whole bunch of noise to this diff. Sorry about that!

All good! I've been noticing that on other branches as well. I think the problem is multiple files. Since each workflow file can have multiple jobs in it I think I'm going to put then all in a QA file. So there will be one run that tests all 3.

**Comment by Snicker7** [comment]
@Colelyman I found an issue that was preventing some of the workflows from running so now they run at the same time and every time there is a test. I haven't changed much but I wanted to check if I was still good to merge into master.

**Comment by Colelyman** [comment]
@Snicker7 looks good to me! I see all of the checks, so I'm good if you are

**Pull request merged**
