### PR TITLE
Mckay/pd warnings

### PR DESCRIPTION
**Pull request by mbowcut2**
These changes fix pandas warnings:

- future deprecation of integer slicing
- future deprecation of errors='ignore'

### CODE REVIEW

**Comment by mbowcut2** [comment]
@Colelyman take a looky here. squash-merge if you like.

**Comment by Colelyman** [comment]
@mbowcut2 after a little digging I realized that the underlying issue is that some of the columns we were trying to convert were strings. What do you think of these changes, to just not convert them instead of swallowing up the exception?

I was also imagining trying to debug an error were a real number wasn't being converted properly... and this way would would at least get some clues to fix that.

**Comment by Colelyman** [comment]
@mbowcut2 but having this in a single function made this super easy to change, so thanks!

**Comment by mbowcut2** [comment]
@Colelyman Yeah, this looks good. I realized the purpose was to ignore string columns (which is why my first try with using 'coerce' was no good) but I was thinking it was simpler to let the try/except weed out the unwanted columns, since they're not the same across dataframes where it's applied.

That being said, I think your design is better for error propagation, and readability.

**Review by Colelyman — APPROVED** [review]
Looks great!

**Pull request merged**
